### ISSUE TITLE
Application crash on playing second video

### ISSUE THREAD

**Issue by TimGels** [fossmium/OneDrive-Cloud-Player#69]
The application sometimes crashes when trying to play the second video in the application session. This can be reproduced on my machine by removing the `graphcache.json` file from the LocalState directory and playing a video for the second time without closing the application in between (so it does not write the cache file).

**Comment by TimGels** [comment]
When navigating to a directory and back before playing a video that resides in the root two times, the application does not crash anymore as a result of the exception that we throw.

**Comment by JohannesKauffmann** [comment]
Exception is thrown in the [video player viewmodel](https://github.com/fossmium/OneDrive-Cloud-Player/blob/0a198596b3b9078cc988e3fa2430e5a2735b599d/OneDrive-Cloud-Player/ViewModels/VideoPlayerPageViewModel.cs#L647), because List.IndexOf returns -1. However, List.Contains returns true.
