### ISSUE TITLE
Audio Starts playing sometimes when it is expected to be quiet.

### ISSUE THREAD

**Issue by TimGels** [fossmium/OneDrive-Cloud-Player#7]

**Comment by GrandDynamo** [comment]
I havent been able to reproduce this problem in [commit](https://github.com/GrandDynamo/OneDrive-Cloud-Player/commit/bd34c10f07a394cb7b1a2cded95346c70ecf799d) but it needs further testing.

The audio does not start muted but is 100% on first startup now.

@JohannesMKauffmann could you test this?

**Comment by GrandDynamo** [comment]
> 
> 
> I havent been able to reproduce this problem in [commit](https://github.com/GrandDynamo/OneDrive-Cloud-Player/commit/bd34c10f07a394cb7b1a2cded95346c70ecf799d) but it needs further testing.
> 
> The audio does not start muted but is 100% on first startup now.
> 
> @JohannesMKauffmann could you test this?

Issue is still present. The issue probably lies with LibVLCSharp (UWP).

**Comment by GrandDynamo** [comment]
We are open to any help on this issue.

**Comment by TimGels** [comment]
Related [merge request](https://code.videolan.org/videolan/vlc/-/merge_requests/558) over at VLC repository.

**Comment by JohannesKauffmann** [comment]
A libvlc fix has been merged ([here](https://code.videolan.org/videolan/vlc/-/merge_requests/558)). Now the volume can be set after the first volumeChanged callback.

**Comment by TimGels** [comment]
Both @JohannesKauffmann and myself have encountered this bug once again. So I will reopen this issue.

**Comment by TimGels** [comment]
Seems to be a regression of #68, so I will close this issue once more.
