### ISSUE TITLE
LogIn Issue

### ISSUE THREAD

**Issue by massmia** [fossmium/OneDrive-Cloud-Player#82]
I am facing login problem. Where the problem? How to solved ?
![ms problem](https://user-images.githubusercontent.com/98101010/181880122-577b3cf3-df63-4819-b267-9a6a24ca5c61.JPG)
![ms 2](https://user-images.githubusercontent.com/98101010/181880125-c8e33172-4cd9-457a-9e54-91dc8dffc161.JPG)

**Comment by TimGels** [comment]
I have not looked into the error in detail due to time constraints at the moment. But at a first glance this seems to be an issue about your account having reached some sort of quota limit. Have you contacted your administrator about it?

**Comment by massmia** [comment]
ok
