### ISSUE TITLE
Cerificate Expired

### ISSUE THREAD

**Issue by williamzerner** [fossmium/OneDrive-Cloud-Player#91]
I recently came across this app and tried to install it. But the certificate expired on 29th May 2023. Today is 13th June 2023. So i couldnt install the certificate. So i couldnt install the app. Please fix this

**Comment by TimGels** [comment]
Thank you for pointing it out. I am not sure when we will have time to fix it. But we will make work of it.

**Comment by JohannesKauffmann** [comment]
This should be done now, release v1.3.0 has updated binaries signed with a new certificate.

**Comment by TimGels** [comment]
@williamzerner  could you confirm this by trying it?

**Comment by williamzerner** [comment]
EDIT: It worked. I was installing the certificate incorrectly. Thank you so much

Old reply:
sorry for the late reply. The certificate is installed (i think no error message) but still unable to install requirements. It seems this issue is only for me. Certain processes are interfering but I cannot shut them down. I am sure the issue is resolved for 99.9% of the people.
